### PR TITLE
Added default root namespace for all projects

### PR DESCRIPTION
**Pull request by alexbereznikov**
Added default root namespace for all projects as discussed in #2

### CODE REVIEW

**Comment by crud89** [comment]
Thank you! 🙂

Just for the sake of consistency, could you write the `SET_PROPERTY` in uppercase?
Also, I don't think that the root namespace should be set to `PROJECT_NAME`. If I recall correctly, each project has it's own root namespace when created in VS. So I think it should actually be set to the target name (i.e. `CSharpLib`, ...).

**Comment by alexbereznikov** [comment]
@Aschratt Done, please take a look once again, sorry for the inconvinience 😊

**Comment by alexbereznikov** [comment]
By the way, according to https://cmake.org/cmake/help/latest/variable/PROJECT_NAME.html:
> This is the name given to the most recently called project() command in the current directory scope or above.

Given that there is a call to `project()` command in the each `CMakeLists.txt` - `${PROJECT_NAME}` in fact evaluates to the different value for each project (as opposed to `${CMAKE_PROJECT_NAME}` which contains top-level project name).

**Comment by alexbereznikov** [comment]
Hey @Aschratt hope you're having a good time! Please take a look once again at the changes 👀

**Comment by crud89** [comment]
Sorry for the delay. I haven't found the time to test it. But I did so now and it works as expected. I will merge the PR now and will change all the hard-wired project name occurrences with `${PROJECT_NAME}`. Thanks for the info! 😊

**Pull request merged**
